### PR TITLE
Add support to manage /etc/hosts.allow

### PR DESCRIPTION
**Pull request by pirzyk**

### CODE REVIEW

**Comment by vbotka** [comment]
Thank you for your contribution! This should be a part of *inetd*. I will merge it and fit the files and namespace afterward.

**Comment by vbotka** [comment]
I updated inetd in devel. Would you like to review it? If there are no objections I'd like to merge it no master next week. There is still TODO: inetd.conf and syslogd.

**Comment by pirzyk** [comment]
Hrm, looking at it I do have some concerns.  inetd is not needed to use hosts.allow.  Any daemon that is compiled with tcp_wrappers (libwrap) will use hosts.allow and they do not need to be started via inetd.  For example I have entries for sshd, sendmail (including on my mail server), and nrpe.

Think I am going to need a day or to to see if I can turn off all the inetd stuff and still have hosts.allow managed.

**Comment by vbotka** [comment]
IMHO, you can use it as is. By default, all actions in *inetd.yml* are off. Except for the last *service* task that ensures *inetd* is started or stopped depending on *fp_inetd_enabled* (default=false). You can enable *fp_inetd=true* and select any tag you need without enabling the *inetd* service. For example,

*  Configure */etc/hosts.allow*

```bash
shell> ansible-playbook pb.yml -t fp_inetd_hosts_allow -e fp_inetd=true
```
* Create a logfile and configure syslog

```bash
shell> ansible-playbook pb.yml -t fp_inetd_syslogd,fp_inetd_logfile -e fp_inetd=true
```
By default, the *inetd* handlers won't restart or reload the service because of *fp_inetd_enabled=false*

**Comment by pirzyk** [comment]
Looks good, sans this one comment typo:
```
diff --git a/tasks/inetd.yml b/tasks/inetd.yml
index a25bada..6274da6 100644
--- a/tasks/inetd.yml
+++ b/tasks/inetd.yml
@@ -110,7 +110,7 @@
   when: fp_inetd_hosts_allow_orig|bool
   tags: fp_inetd_hosts_allow_orig
 
-- name: "inetd: Configure {{ fp_hosts_allow_file }}"
+- name: "inetd: Configure {{ fp_inetd_hosts_allow_file }}"
   ansible.builtin.template:
     src: "{{ fp_inetd_hosts_allow_template }}"
     dest: "{{ fp_inetd_hosts_allow_file }}"
```

**Comment by vbotka** [comment]
Fixed in *devel*. Thank you!

**Pull request merged**
