### PR TITLE
Add newsyslog entry for the connections.log file

### PR DESCRIPTION
**Pull request by pirzyk**

### CODE REVIEW

**Comment by vbotka** [comment]
Thank you for your contribution!

**Comment by vbotka** [comment]
LGTM. I added the *debug.yml* entry and updated the *inetd.yml.sample*. An entry in *fp_inetd_syslogd_newconfd* and *fp_inetd_logfile* should be mutually exclusive. If missing, the 'create newsyslog' handler will create the log file.

**Comment by pirzyk** [comment]
Doh, I keep forgetting the debug.yml entry...

**Comment by vbotka** [comment]
I rebased *devel* (there are a couple of unrelated commits) on top of *staging*, updated docs, and updated tags in defaults/sanity.yml. JFYI, sanity, if enabled, is testing the validity of `[-t  TAGS]`.

I merged *devel* to *master* and tag 2.6.6

**Comment by vbotka** [comment]
JFYI,

The role updated to 2.6.6. in Ansible Galaxy
https://galaxy.ansible.com/ui/standalone/roles/vbotka/freebsd_postinstall/install/

Docs updated
https://ansible-freebsd-postinstall.readthedocs.io/en/latest/

Started devel of 2.6.7
https://github.com/vbotka/ansible-freebsd-postinstall/tree/devel

**Pull request merged**
