### PR TITLE
Add support to manage /etc/freebsd-update.conf

### PR DESCRIPTION
**Pull request by pirzyk**

### CODE REVIEW

**Comment by vbotka** [comment]
Thank you very much! I briefly reviewed the PR. It looks good to me. Could you submit it to the devel branch? We will have to find a way to make the defaults idempotent. I mean, a play must report no changes when a user makes no changes to the defaults.

**Comment by pirzyk** [comment]
Doh!

After I file several PRs.  Maybe I can edit the existing ones to be off the devel branch.  Let me look into it.
- JimP

**Comment by pirzyk** [comment]
OK updated the branch on all 6 PRs that I opened.  Let me know if I missed anyone.  Thanks and sorry for the misstep.

**Review by vbotka — APPROVED** [review]
LGTM. Let's test it in devel.

**Comment by pirzyk** [comment]
While starting to test the fp_inetd* stuff, I ran across this issue with the fp_freebsd_update changes:
```
TASK [ansible-role-freebsd-postinstall : freebsd-update: Protect trusted keyprint] *************************************************************************************************************************
fatal: [amigo.home.pirzyk.org]: FAILED! => {"msg": "The conditional check 'fp_freebsd_update_conf.keyprint == fp_freebsd_update_KeyPrint' failed. The error was: error while evaluating conditional (fp_freebsd_update_conf.keyprint == fp_freebsd_update_KeyPrint): 'dict object' has no attribute 'keyprint'. 'dict object' has no attribute 'keyprint'"}
```

This was on applying the changes to the templates (added commented out lines, no changes to the KeyPrint value).  Thoughts?

**Comment by vbotka** [comment]
I can't reproduce it. The idea is to read the current configuration of /etc/freebsd-update.conf into the dictionary *fp_freebsd_update_conf* and compare the current key *fp_freebsd_update_conf.keyprint* with the variable *fp_freebsd_update_KeyPrint*. Please, try the below steps

1) Run tag *fp_freebsd_update_getconf* and enable *fp_freebsd_update_debug=true*. You should see the attribute *keyprint*

```yaml
shell> ansible-playbook pb.yml -t fp_freebsd_update_getconf -e fp_freebsd_update=true -e fp_freebsd_update_debug=true

  ...

TASK [vbotka.freebsd_postinstall : freebsd-update: Debug fp_freebsd_update_conf] *************
ok: [test] => 
  fp_freebsd_update_conf:
    allowadd: 'yes'
    allowdelete: 'yes'
    backupkernel: 'yes'
    backupkerneldir: /boot/kernel.old
    backupkernelsymbolfiles: 'no'
    basedir: /
    components: world kernel
    idsignorepaths: /usr/share/man/cat /usr/share/man/whatis /var/db/locate.database /var/log
    ignorepaths: ''
    keepmodifiedmetadata: 'yes'
    keyprint: 800651ef4b4c71c27e60786d7b487188970f4b4169cc055784e21eb71d410cc5
```

2) Run the tag *fp_freebsd_update_protect_keyprint*. You should see the assert to pass

```yaml
shell> ansible-playbook pb.yml -t fp_freebsd_update_protect_keyprint -e fp_freebsd_update=true

  ...

TASK [vbotka.freebsd_postinstall : freebsd-update: Protect trusted keyprint] ******************************************************************************************************************
ok: [test] => changed=false 
  msg: '[OK]  KeyPrint will not change.'
```

3) The assert shall pass also when running the whole fp_freebsd_update* 

```bash
shell> ansible-playbook pb.yml -t fp_freebsd_update -e fp_freebsd_update=true
```
Yesterday I tested complete *devel* on a couple of 13.2 boxes with no issues

```bash
shell> ansible-playbook pb.yml
```

**Comment by vbotka** [comment]
> ... issue with the fp_freebsd_update changes

I know nothing about *fp_freebsd_update changes*. You might want to update the fresh *devel* branch.

**Comment by pirzyk** [comment]
OK I found the source of the problem, case!
```
TASK [ansible-role-freebsd-postinstall : freebsd-update: Debug fp_freebsd_update_conf] *********************************************************************************************************************
ok: [amigo.home.pirzyk.org] => {
    "fp_freebsd_update_conf": {
        "ALLOWADD": "yes",
        "ALLOWDELETE": "yes",
        "BACKUPKERNEL": "yes",
        "BACKUPKERNELDIR": "/boot/kernel.old",
        "BACKUPKERNELSYMBOLFILES": "no",
        "BASEDIR": "/",
        "COMPONENTS": "src world kernel",
        "IDSIGNOREPATHS": "/usr/share/man/cat /usr/share/man/whatis /var/db/locate.database /var/log",
        "IGNOREPATHS": "",
        "KEEPMODIFIEDMETADATA": "yes",
        "KEYPRINT": "800651ef4b4c71c27e60786d7b487188970f4b4169cc055784e21eb71d410cc5",
        "MAILTO": "root",
        "MERGECHANGES": "/etc/ /boot/device.hints",
        "SERVERNAME": "update.FreeBSD.org",
        "STRICTCOMPONENTS": "no",
        "TARGETRELEASE": "",
        "UPDATEIFUNMODIFIED": "/etc/ /var/ /root/ /.cshrc /.profile",
        "VERBOSELEVEL": "stats",
        "WORKDIR": "/var/db/freebsd-update"
    }
}
```

when I changed the tasks to compare to `fp_freebsd_update_conf.KEYPRINT`, it works as expected.  I'm wondering if this is a python module version (or platform) issue.  I am running the ansible controller from Mac OS X.

**Comment by vbotka** [comment]
Thank you! I fixed the case to KEYPRINT. This should have been obvious from the very beginning. The key in the file is uppercase. It's not *jc* business to change the case of the keys. Sorry.

JFYI, on my side, this was an Ubuntu jc package problem. The problem was Ubuntu 22.04 with Python 3.10 and jc 1.17.3-1 from the package converting the case. The problem was gone when I installed jc 1.24.0 from PyPI. FreeBSD package textproc/py-jc (py39-jc) works fine too.

**Comment by vbotka** [comment]
I completed the implementation and merged devel into the staging. If there are no objections I'll merge it to master and tag 2.6.6. in a couple of days.

Additional changes:

* The variable fp_inetd_syslogd_conf renamed to fp_inetd_syslogd_confd
* Unify format of fp_inetd_syslogd_confd and fp_syslogd_confd. See vars/samples
* Use single template syslog.conf.j2 both for syslog.conf and syslog.d/*
* Template syslogd_conf.j2 removed

**Comment by pirzyk** [comment]
> Unify format of fp_inetd_syslogd_confd and fp_syslogd_confd. See vars/samples

One thing I see looking at this is there is no management of the log file in newsyslog config, which I missed.  Might want to add it, or should it be done via the generic syslogd/newsyslog tasks?

**Comment by vbotka** [comment]
(I was too quick. Now I understand your question.) Add it if you want to. Create variable *fp_inetd_syslogd_newconfd*.

**Pull request merged**
